name: Frontend Lints (ESLint)
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: ESLint
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx