name: Frontend Lints (ESLint)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: ESLint
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: npm run lint